### ISSUE TITLE
Add Graph Support

### ISSUE THREAD

**Issue by Minitour** [Minitour/wapy-backend#11]
```typescript
type GraphData = {
  data: any,
  type: string,
  showLegend: boolean,
  name: string,
  header: string
}

```

For line chart:
https://www.chartjs.org/docs/latest/charts/line.html

For bar chart:
https://www.chartjs.org/docs/latest/charts/bar.html

For radar chart:
https://www.chartjs.org/docs/latest/charts/radar.html

Pie:
https://www.chartjs.org/docs/latest/charts/doughnut.html

**Comment by TomerGoldfeder** [comment]
added support for line and bar charts

left: radar(spider) chart
(pie chart for now is not used in this project)

**Comment by Minitour** [comment]
Reactions chart not working:

<img width="567" alt="Screen Shot 2019-05-24 at 19 28 10" src="https://user-images.githubusercontent.com/17438617/58342815-1c644300-7e5a-11e9-9ec8-3f154a725bff.png">

```json
{"type":"bar","name":"Reactions","showLegend":false,"header":"Reactions","data":{"dataset":[{"data":[{"x":"calm","y":0},{"x":"happy","y":0},{"x":"confused","y":0},{"x":"disgusted","y":0},{"x":"angry","y":0},{"x":"sad","y":0},{"x":"surprised","y":0}]}]}}

```

**Comment by Minitour** [comment]
Exposures partially working.

<img width="566" alt="Screen Shot 2019-05-24 at 19 28 16" src="https://user-images.githubusercontent.com/17438617/58342891-5d5c5780-7e5a-11e9-80dc-07154de5bfa5.png">

Label is shown as undefined instead of showing X value.

**Comment by Minitour** [comment]
@TomerGoldfeder reimplement the charts properly.
Here are better examples.

https://tobiasahlin.com/blog/chartjs-charts-to-get-you-started/

Note:
You can now also provide `options` field.

**Comment by Minitour** [comment]
Here is the updated model:
```typescript
type GraphData = {
  type: string, // The type of the chart
  data: any // The data
  options: any // The options
  name: string, // The graph name
  header: string // graph header
}
```
