### ISSUE TITLE
Provide APIs

### ISSUE THREAD

**Issue by Minitour** [Minitour/wapy-backend#12]
Provide postman body / headers POST parameters for APIs other than dashboard.

**Comment by TomerGoldfeder** [comment]
For all controllers the payload should be:
payload:
`{
                "owner_uid" : "1",
                "fromTime": "2019-04-12 12:34:12",
                "toTime": "2019-04-12 12:45:12"
}`

API call:
**Box Controller:**
http://ip_address:port/box/:box_id

**Product Controller:**
http://ip_address:port/product/:product_id

**Dashboard Controller:**
http://ip_address:port/dashboard

**Comment by Minitour** [comment]
Didn't we change it so that instead of sending a time range we only send a date and a number of days?

**Comment by TomerGoldfeder** [comment]
sorry, my bad, copied the wrong one
this is the right one:
`{
            "owner_uid" : "1",
            "toTime": "2019-04-12 12:34:12",
            "numberOfDays": 7
}`
