### ISSUE TITLE
Empty table / No charts for BoxDashboard?

### ISSUE THREAD

**Issue by Minitour** [Minitour/wapy-backend#14]
<img width="1112" alt="Screen Shot 2019-06-04 at 0 07 34" src="https://user-images.githubusercontent.com/17438617/58834730-bdbe7680-865c-11e9-9560-6d608cc52d36.png">
<img width="1119" alt="Screen Shot 2019-06-04 at 0 07 46" src="https://user-images.githubusercontent.com/17438617/58834727-bc8d4980-865c-11e9-8e8c-8aeeb6fa6cb5.png">

**Comment by TomerGoldfeder** [comment]
fixed for dashboard and box controllers

for all controllers - if there is no data -> will put empty graph/table/stats
