### ISSUE TITLE
Replace Camera ID with User ID in Dashboard Access

### ISSUE THREAD

**Issue by Minitour** [Minitour/wapy-backend#4]
The dashboard should show general information for a certain account. Therefor the query should not be per camera but per account. 

Update the tables to also contain a uid (User ID) which is already provided with the MMO as the field `owner_uid`.

Then replace and update the queries (Query by account and not by camera).

**Comment by TomerGoldfeder** [comment]
updated the following files:
1. camera_service script - extract the owner_uid from the mom data, saving the image with the owner_uid to s3, send to kinesis the owner_uid along with the object that has beed detected.

2. lambda functions - the images and the object functions will get the owner uid and insert to the sql tables

3. java backend - adjusted the queries to search according to owner_uid and not camera_id
 
sql tables has been altered properly.
